// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwaxlgshrygrudtcgfco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3YXhsZ3NocnlncnVkdGNnZmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjgzMzksImV4cCI6MjA2MDE0NDMzOX0.PvKeF8DXscidfKkX_mfRf91l8PvpeZhnJ_E9E933kLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);